#!/bin/sh

##
# Install these files
#
# Syntax:
#
#     install [dir [dot]]
#
# Install for the current user:
#
#     install
#
# Install for all users:
#
#     install /etc
#
# Install for any path:
#
#     install /foo/goo/hoo
#
# Install for any path plus use a dot prefix to make the files hidden:
#
#     install /foo/goo/hoo .
#
##

if [ "$#" -eq 0 ]; then
  echo "zero"
  dir="$HOME"
  dot="."
else
  echo "some"
  dir="$1"
  dot="$2"
fi

for x in bash_aliases bash_aliases.d bash_completion bash_completions.d bash_functions bash_functions.d bash_scripts bash_scripts.d bashrc bashrc_on_cygwin bashrc_on_darwin bashrc_on_linux; do
  cp -R "$x" "$dir/$dot$x"
done
