#!/bin/sh

##
# Install these files
#
# Syntax:
#
#     ./install [dir [dot]]
#
# Install for the current user:
#
#     ./install
#
# Install for all users, which may need sudo or root permission:
#
#     sudo ./install /etc
#
# Install for any path:
#
#     sudo ./install /foo/goo/hoo
#
# Install for any path plus use a dot prefix to make the files hidden:
#
#     sudo ./install /foo/goo/hoo .
#
##

if [ "$#" -eq 0 ]; then
  dir="$HOME"
  dot="."
else
  dir="$1"
  dot="$2"
fi

dst="$dir/$dot$x"
if [ -e "$dst" ]; then
    echo "Skipping $x because path aleady exists: $dst"
    exit 1
fi
cp -R "bash.d" "$dst"
