#!/bin/sh

##
# Install these files
#
# Syntax:
#
#     ./install [dir [dot]]
#
# Install for the current user:
#
#     ./install
#
# Install for all users, which may need sudo or root permission:
#
#     sudo ./install /etc
#
# Install for any path:
#
#     sudo ./install /foo/goo/hoo
#
# Install for any path plus use a dot prefix to make the files hidden:
#
#     sudo ./install /foo/goo/hoo .
#
##

if [ "$#" -eq 0 ]; then
  dir="$HOME"
  dot="."
else
  dir="$1"
  dot="$2"
fi

for x in bash_aliases bash_aliases.d bash_completion bash_completion.d bash_functions bash_functions.d bash_scripts bash_scripts.d bashrc bash_on_cygwin bash_on_darwin bash_on_linux; do
  dst="$dir/$dot$x"
  if [ -e "$dst" ]; then 
    echo "Skipping $x because path aleady exists: $dst"
  else 
    cp -R "$x" "$dst"
  fi
done
